import{api,buildApiUrl}from'./api-client.js';
export const resumeService={
  eligibility:()=>api.get('/resume-service/eligibility'),
  list:()=>api.get('/resume-requests'),
  detail:(id)=>api.get(`/resume-requests/${encodeURIComponent(id)}`),
  create:(data)=>api.post('/resume-requests',data,{skipRefresh:true}),
  revision:(id,notes)=>api.post(`/resume-requests/${encodeURIComponent(id)}/revision`,{notes},{skipRefresh:true}),
  upload:(id,role,file)=>{const form=new FormData();form.set('role',role);form.set('file',file);return api.post(`/resume-requests/${encodeURIComponent(id)}/files`,form,{skipRefresh:true});},
  fileDownloadUrl:(id,fileId)=>buildApiUrl(`/resume-requests/${encodeURIComponent(id)}/files/${encodeURIComponent(fileId)}/download`),
  downloadUrl:(id)=>buildApiUrl(`/resume-requests/${encodeURIComponent(id)}/deliverables/current/download`),
  adminQueue:()=>api.get('/admin/resume-requests'),
  adminDetail:(id)=>api.get(`/admin/resume-requests/${encodeURIComponent(id)}`),
  assign:(id,specialistPublicId,reason)=>api.post(`/admin/resume-requests/${encodeURIComponent(id)}/assign`,{specialistPublicId,reason},{skipRefresh:true}),
  requestInformation:(id,reason)=>api.post(`/admin/resume-requests/${encodeURIComponent(id)}/request-information`,{reason},{skipRefresh:true}),
  markDataComplete:(id,reason)=>api.post(`/admin/resume-requests/${encodeURIComponent(id)}/mark-data-complete`,{reason},{skipRefresh:true}),
  start:(id,reason)=>api.post(`/admin/resume-requests/${encodeURIComponent(id)}/start`,{reason},{skipRefresh:true}),
  startRevision:(id,reason)=>api.post(`/admin/resume-requests/${encodeURIComponent(id)}/revision-start`,{reason},{skipRefresh:true}),
  registerDeliverable:(id,data)=>api.post(`/admin/resume-requests/${encodeURIComponent(id)}/deliverables`,data,{skipRefresh:true}),
  release:(id,data)=>api.post(`/admin/resume-requests/${encodeURIComponent(id)}/complete`,data,{skipRefresh:true}),
  statistics:()=>api.get('/admin/statistics'),
};
